version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  - package-ecosystem: github-actions
    directory: / # default location of `.github/workflows`
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]
