version: 2
updates:
  - package-ecosystem: github-actions
    directory: / # default location of `.github/workflows`
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]
