module.exports = {
  someSidebar: {
    '🌀 MetaOS': ['home'],
    '🤨 Pillar Memes': [
      'wtf-is-metagame/origin-story',
      'wtf-is-metagame/in-search-of-commons-that-scale',
      'wtf-is-metagame/the-coming-of-metagame',
      'wtf-is-metagame/way-of-web3-founders',
      'wtf-is-metagame/narrative-1-a-decentralized-factory',
      'wtf-is-metagame/narrative-2-a-web-of-opportunity',
      'wtf-is-metagame/metafam-way',
    ],
    '🧐 Understanding MetaGame': [
      'wtf-is-metagame/wtf-is-metagame',
      'how-does-it-work/phases-of-metagame',
      'how-does-it-work/how-metagame-works',
      'how-does-it-work/xp',
      'how-does-it-work/obtaining-seeds',
      'how-does-it-work/become-a-founder-of-metagame',
    ],
    '🗺 Enter MetaGame': [
      'enter-metagame/join-metagame',
      'enter-metagame/how-to-become-a-player',
      'enter-metagame/roles-in-metagame',
      'enter-metagame/navigation-board',
      'enter-metagame/leaderboard',
      'enter-metagame/Chainlog',
    ],
    '🏡 The Great Houses': [
      'great-houses/house-of-ethereum',
      'great-houses/house-of-daos',
      'great-houses/house-of-NFTs',
      'enter-metagame/guilds-of-metagame',
      //   'great-houses/house-of-defiance',
      //   'great-houses/house-of-dapps',
      //   'great-houses/house-of-tokens',
    ],
    '⚔️ Guilding': [
      'Guilding/metasys',
      'Guilding/what-why-how-of-your-dao',
      'Guilding/guilding-101',
      'Guilding/building-successful-teams',
    ],

    '🌳 Other': [
      'resources/glossary',
      'resources/graphics',
      'resources/art',
      'resources/memes',
      'resources/talks',
      // 'resources/alignment2021',
    ],
    // "About The Wiki": ["style-guide", "mdx"],
  },
};
