-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO "LinkType" (type, description) VALUES
--   ('Discord', 'DISCORD'),
--   ('Twitter', 'TWITTER'),
--   ('Lenster', 'LENSTER'),
--   ('Farcaster', 'FARCASTER'),
--   ('Github', 'GITHUB'),
--   ('Telegram', 'TELEGRAM'),
--   ('Youtube', 'YOUTUBE');
