DELETE FROM "Skill";

DELETE FROM "SkillCategory" WHERE name NOT IN ('COMMUNITY', 'ENGINEERING', 'TECHNOLOGIES');

INSERT INTO "SkillCategory" (name) VALUES
    ('DESIGN'),
    ('DEV'),
    ('STRATEGY');

INSERT INTO "Skill" (name, category)
VALUES ('Architecture', 'DESIGN') ,
       ('Fashion Design', 'DESIGN') ,
       ('Graphics Design', 'DESIGN') ,
       ('Art / Illustration', 'DESIGN') ,
       ('UI / UX Design', 'DESIGN') ,
       ('Web Design', 'DESIGN') ,
       ('Audiovisual', 'DESIGN') ,
       ('Industrial Design', 'DESIGN') ,
       ('Motion Graphics', 'DESIGN') ,
       ('Photography', 'DESIGN') ,
       ('Video Production', 'DESIGN') ,
       ('Accounting', 'STRATEGY') ,
       ('Branding', 'STRATEGY') ,
       ('Business Development', 'STRATEGY') ,
       ('Product Development', 'STRATEGY') ,
       ('Communications', 'STRATEGY') ,
       ('Customer Service', 'STRATEGY') ,
       ('Finance', 'STRATEGY') ,
       ('Legal', 'STRATEGY') ,
       ('Marketing / Sales', 'STRATEGY') ,
       ('Operations', 'STRATEGY') ,
       ('Recruiting', 'STRATEGY') ,
       ('Moderation', 'COMMUNITY') ,
       ('Community Cultivation', 'COMMUNITY') ,
       ('Learning & Education', 'COMMUNITY') ,
       ('Ops / Coordination', 'COMMUNITY') ,
       ('Content Creation', 'COMMUNITY') ,
       ('Social Media', 'COMMUNITY') ,
       ('Memes', 'COMMUNITY') ,
       ('Project Management', 'DEV') ,
       ('Backend Development', 'DEV') ,
       ('DevOps', 'DEV') ,
       ('Frontend Development', 'DEV') ,
       ('Software Engineering', 'DEV') ,
       ('Mobile Development', 'DEV') ,
       ('Smart Contracts', 'DEV') ,
       ('Security / Auditing', 'DEV') ,
       ('Game Development', 'DEV') ,
       ('Token Engineering', 'ENGINEERING') ,
       ('Research', 'ENGINEERING') ,
       ('Computer Science', 'ENGINEERING') ,
       ('Governance Design', 'ENGINEERING') ,
       ('Cryptography', 'ENGINEERING') ,
       ('Data Science', 'ENGINEERING') ,
       ('Mechanism Design', 'ENGINEERING') ,
       ('Economics', 'ENGINEERING') ,
       ('Simulations', 'ENGINEERING') ,
       ('Mathematics', 'ENGINEERING') ,
       ('Statistics', 'ENGINEERING') ,
       ('Machine Learning / AI', 'ENGINEERING') ,
       ('Node.js', 'TECHNOLOGIES') ,
       ('React', 'TECHNOLOGIES') ,
       ('React Native', 'TECHNOLOGIES') ,
       ('GraphQL', 'TECHNOLOGIES') ,
       ('MongoDB', 'TECHNOLOGIES') ,
       ('PostgreSQL', 'TECHNOLOGIES') ,
       ('MySQL', 'TECHNOLOGIES') ,
       ('Elasticsearch', 'TECHNOLOGIES') ,
       ('Redis', 'TECHNOLOGIES') ,
       ('Firebase', 'TECHNOLOGIES') ,
       ('Docker', 'TECHNOLOGIES') ,
       ('Kubernetes', 'TECHNOLOGIES') ,
       ('Serverless', 'TECHNOLOGIES') ,
       ('Javascript', 'TECHNOLOGIES') ,
       ('TypeScript', 'TECHNOLOGIES') ,
       ('Solidity', 'TECHNOLOGIES') ,
       ('Vyper', 'TECHNOLOGIES') ,
       ('C', 'TECHNOLOGIES') ,
       ('C#', 'TECHNOLOGIES') ,
       ('C++', 'TECHNOLOGIES') ,
       ('CSS', 'TECHNOLOGIES') ,
       ('Go', 'TECHNOLOGIES') ,
       ('HTML', 'TECHNOLOGIES') ,
       ('Java', 'TECHNOLOGIES') ,
       ('Objective-C', 'TECHNOLOGIES') ,
       ('Perl', 'TECHNOLOGIES') ,
       ('PHP', 'TECHNOLOGIES') ,
       ('Dart', 'TECHNOLOGIES') ,
       ('Swift', 'TECHNOLOGIES') ,
       ('Haskell', 'TECHNOLOGIES') ,
       ('Scala', 'TECHNOLOGIES') ,
       ('Kotlin', 'TECHNOLOGIES') ,
       ('Python', 'TECHNOLOGIES') ,
       ('Ruby', 'TECHNOLOGIES') ,
       ('Flutter', 'TECHNOLOGIES') ,
       ('NextJS', 'TECHNOLOGIES') ,
       ('Gatsby', 'TECHNOLOGIES') ,
       ('Vue', 'TECHNOLOGIES') ,
       ('Angular', 'TECHNOLOGIES') ,
       ('Django', 'TECHNOLOGIES') ,
       ('Svelte', 'TECHNOLOGIES') ,
       ('Cordova', 'TECHNOLOGIES') ,
       ('Unity 3D', 'TECHNOLOGIES') ,
       ('Blender', 'TECHNOLOGIES') ,
       ('Adobe CC', 'TECHNOLOGIES');
