INSERT INTO "Skill" (name, category)
VALUES ('Architecture', 'CREATIVE'),
       ('Fashion Design', 'CREATIVE'),
       ('Graphics Design', 'CREATIVE'),
       ('Art / Illustration', 'CREATIVE'),
       ('Audiovisual', 'CREATIVE'),
       ('Industrial Design', 'CREATIVE'),
       ('Motion Graphics', 'CREATIVE'),
       ('Photography', 'CREATIVE'),
       ('Video Production', 'CREATIVE'),
       ('Accounting', 'BUSINESS'),
       ('Branding', 'BUSINESS'),
       ('Business Development', 'BUSINESS'),
       ('Strategy / Consulting', 'BUSINESS'),
       ('Communications', 'BUSINESS'),
       ('Customer Service', 'BUSINESS'),
       ('Finance', 'BUSINESS'),
       ('Human Resources', 'BUSINESS'),
       ('Learning & Education', 'BUSINESS'),
       ('Legal', 'BUSINESS'),
       ('Marketing / Sales', 'BUSINESS'),
       ('Operations', 'BUSINESS'),
       ('Partnerships', 'BUSINESS'),
       ('Recruiting', 'BUSINESS'),
       ('Moderation', 'COMMUNITY'),
       ('Community Cultivation', 'COMMUNITY'),
       ('Ops / Coordination', 'COMMUNITY'),
       ('Content Creation', 'COMMUNITY'),
       ('Social Media', 'COMMUNITY'),
       ('Memes', 'COMMUNITY'),
       ('Backend Development', 'ENGINEERING'),
       ('DevOps', 'ENGINEERING'),
       ('Frontend Development', 'ENGINEERING'),
       ('Mobile Development', 'ENGINEERING'),
       ('Software Engineering', 'ENGINEERING'),
       ('Smart Contracts', 'ENGINEERING'),
       ('Security / Auditing', 'ENGINEERING'),
       ('Game Development', 'ENGINEERING'),
       ('Data Analytics', 'PRODUCT'),
       ('Product Design', 'PRODUCT'),
       ('Token Engineering', 'PRODUCT'),
       ('Governance Design', 'PRODUCT'),
       ('Project Management', 'PRODUCT'),
       ('Research & Development', 'PRODUCT'),
       ('UI / UX Design', 'PRODUCT'),
       ('Computer Science', 'SCIENCE'),
       ('Cryptography', 'SCIENCE'),
       ('Data Science', 'SCIENCE'),
       ('Economics', 'SCIENCE'),
       ('Mathematics', 'SCIENCE'),
       ('Statistics', 'SCIENCE'),
       ('Machine Learning / AI', 'SCIENCE'),
       ('Node.js', 'TECHNOLOGIES'),
       ('React', 'TECHNOLOGIES'),
       ('React Native', 'TECHNOLOGIES'),
       ('GraphQL', 'TECHNOLOGIES'),
       ('MongoDB', 'TECHNOLOGIES'),
       ('PostgreSQL', 'TECHNOLOGIES'),
       ('MySQL', 'TECHNOLOGIES'),
       ('Elasticsearch', 'TECHNOLOGIES'),
       ('Redis', 'TECHNOLOGIES'),
       ('Firebase', 'TECHNOLOGIES'),
       ('Docker', 'TECHNOLOGIES'),
       ('Kubernetes', 'TECHNOLOGIES'),
       ('Serverless', 'TECHNOLOGIES'),
       ('Javascript', 'TECHNOLOGIES'),
       ('TypeScript', 'TECHNOLOGIES'),
       ('Solidity', 'TECHNOLOGIES'),
       ('Vyper', 'TECHNOLOGIES'),
       ('C', 'TECHNOLOGIES'),
       ('C#', 'TECHNOLOGIES'),
       ('C++', 'TECHNOLOGIES'),
       ('CSS', 'TECHNOLOGIES'),
       ('Go', 'TECHNOLOGIES'),
       ('HTML', 'TECHNOLOGIES'),
       ('Java', 'TECHNOLOGIES'),
       ('Objective-C', 'TECHNOLOGIES'),
       ('Perl', 'TECHNOLOGIES'),
       ('PHP', 'TECHNOLOGIES'),
       ('Dart', 'TECHNOLOGIES'),
       ('Swift', 'TECHNOLOGIES'),
       ('Haskell', 'TECHNOLOGIES'),
       ('Scala', 'TECHNOLOGIES'),
       ('Kotlin', 'TECHNOLOGIES'),
       ('Python', 'TECHNOLOGIES'),
       ('Ruby', 'TECHNOLOGIES'),
       ('Flutter', 'TECHNOLOGIES'),
       ('NextJS', 'TECHNOLOGIES'),
       ('Gatsby', 'TECHNOLOGIES'),
       ('Vue', 'TECHNOLOGIES'),
       ('Angular', 'TECHNOLOGIES'),
       ('Django', 'TECHNOLOGIES'),
       ('Svelte', 'TECHNOLOGIES'),
       ('Cordova', 'TECHNOLOGIES'),
       ('Unity 3D', 'TECHNOLOGIES'),
       ('Blender', 'TECHNOLOGIES'),
       ('Adobe CC', 'TECHNOLOGIES');
