export enum BoxType {
  PLAYER_HERO = 'player-hero',
  PLAYER_SKILLS = 'player-skills',
  PLAYER_NFT_GALLERY = 'player-nft-gallery',
  PLAYER_DAO_MEMBERSHIPS = 'player-dao-memberships',
  PLAYER_ACHIEVEMENTS = 'player-achievements',
  PLAYER_TYPE = 'player-type',
  PLAYER_COLOR_DISPOSITION = 'player-color-disposition',
  PLAYER_ROLES = 'player-roles',
  PLAYER_ADD_BOX = 'player-add-box',
  GUILD_SKILLS = 'guild-skills',
  GUILD_GALLERY = 'guild-gallery',
  GUILD_ANNOUNCEMENTS = 'guild-announcements',
  GUILD_PLAYERS = 'guild-players',
  GUILD_QUESTS = 'quild-quests',
  GUILD_STATS = 'guild-stats',
  GUILD_LINKS = 'guild-links',
}
