-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."guild" add column "updated_at" timestamptz
--  null default now();
