export default [
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'meToken',
        type: 'address',
      },
    ],
    name: 'CancelResubscribe',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'from',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'meToken',
        type: 'address',
      },
    ],
    name: 'CancelTransferMeTokenOwnership',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'from',
        type: 'address',
      },
      { indexed: false, internalType: 'address', name: 'to', type: 'address' },
      {
        indexed: false,
        internalType: 'address',
        name: 'meToken',
        type: 'address',
      },
    ],
    name: 'ClaimMeTokenOwnership',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'meToken',
        type: 'address',
      },
    ],
    name: 'FinishResubscribe',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'meToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'targetHubId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'migration',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'bytes',
        name: 'encodedMigrationArgs',
        type: 'bytes',
      },
    ],
    name: 'InitResubscribe',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'meToken',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'minted',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'asset',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'assetsDeposited',
        type: 'uint256',
      },
      { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      {
        indexed: false,
        internalType: 'string',
        name: 'symbol',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'hubId',
        type: 'uint256',
      },
    ],
    name: 'Subscribe',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'from',
        type: 'address',
      },
      { indexed: false, internalType: 'address', name: 'to', type: 'address' },
      {
        indexed: false,
        internalType: 'address',
        name: 'meToken',
        type: 'address',
      },
    ],
    name: 'TransferMeTokenOwnership',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'bool', name: 'add', type: 'bool' },
      {
        indexed: false,
        internalType: 'address',
        name: 'meToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'UpdateBalanceLocked',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'bool', name: 'add', type: 'bool' },
      {
        indexed: false,
        internalType: 'address',
        name: 'meToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'UpdateBalancePooled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'meToken',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newBalance',
        type: 'uint256',
      },
    ],
    name: 'UpdateBalances',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'address', name: 'meToken', type: 'address' }],
    name: 'cancelResubscribe',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'cancelTransferMeTokenOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'oldOwner', type: 'address' }],
    name: 'claimMeTokenOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'meToken', type: 'address' }],
    name: 'finishResubscribe',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'uint256', name: 'hubId', type: 'uint256' },
          { internalType: 'uint256', name: 'balancePooled', type: 'uint256' },
          { internalType: 'uint256', name: 'balanceLocked', type: 'uint256' },
          { internalType: 'uint256', name: 'startTime', type: 'uint256' },
          { internalType: 'uint256', name: 'endTime', type: 'uint256' },
          { internalType: 'uint256', name: 'targetHubId', type: 'uint256' },
          { internalType: 'address', name: 'migration', type: 'address' },
        ],
        internalType: 'struct MeTokenInfo',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'meToken', type: 'address' }],
    name: 'getBasicMeTokenInfo',
    outputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'uint256', name: 'hubId', type: 'uint256' },
      { internalType: 'uint256', name: 'balancePooled', type: 'uint256' },
      { internalType: 'uint256', name: 'balanceLocked', type: 'uint256' },
      { internalType: 'address', name: 'migration', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'meToken', type: 'address' }],
    name: 'getMeTokenInfo',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'uint256', name: 'hubId', type: 'uint256' },
          { internalType: 'uint256', name: 'balancePooled', type: 'uint256' },
          { internalType: 'uint256', name: 'balanceLocked', type: 'uint256' },
          { internalType: 'uint256', name: 'startTime', type: 'uint256' },
          { internalType: 'uint256', name: 'endTime', type: 'uint256' },
          { internalType: 'uint256', name: 'targetHubId', type: 'uint256' },
          { internalType: 'address', name: 'migration', type: 'address' },
        ],
        internalType: 'struct MeTokenInfo',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'getOwnerMeToken',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'oldOwner', type: 'address' }],
    name: 'getPendingOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'meToken', type: 'address' },
      { internalType: 'uint256', name: 'targetHubId', type: 'uint256' },
      { internalType: 'address', name: 'migration', type: 'address' },
      { internalType: 'bytes', name: 'encodedMigrationArgs', type: 'bytes' },
    ],
    name: 'initResubscribe',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'isOwner',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'meTokenDuration',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'meTokenWarmup',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'period', type: 'uint256' }],
    name: 'setMeTokenDuration',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'period', type: 'uint256' }],
    name: 'setMeTokenWarmup',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'symbol', type: 'string' },
      { internalType: 'uint256', name: 'hubId', type: 'uint256' },
      { internalType: 'uint256', name: 'assetsDeposited', type: 'uint256' },
    ],
    name: 'subscribe',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferMeTokenOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'meToken', type: 'address' },
      { internalType: 'uint256', name: 'newBalance', type: 'uint256' },
    ],
    name: 'updateBalances',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
