name: Deploy Preview to Cloud Run

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize

env:
  PROJECT_ID: metagame-thegame
  REGISTRY_REGION: us-east4
  REGISTRY_REPO: thegame
  DEPLOYMENT_DOMAIN: a.run.app
  CLOUDRUN_SUFFIX: mjhnbmqqna-uk
  DB_NAME: hasura-pr-${{github.event.number}}
  BACKEND_SERVICE: backend-pr-${{github.event.number}}
  FRONTEND_SERVICE: frontend-pr-${{github.event.number}}
  BACKEND_PORT: 4000
  HASURA_PORT: 8080
  FRONTEND_PORT: 3000

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      CLOUDRUN_REGION: ${{env.REGISTRY_REGION}}
      CLOUDSQL_INSTANCE_NAME: ${{env.REGISTRY_REPO}}
      CLOUDSQL_CONNECTION_NAME: ${{env.PROJECT_ID}}:${{env.REGISTRY_REGION}}:${{env.REGISTRY_REPO}}
      GRAPHQL_HOST: ${{env.DB_NAME}}-${{env.CLOUDRUN_SUFFIX}}
      GRAPHQL_URL: https://${{env.GRAPHQL_HOST}}.${{env.DEPLOYMENT_DOMAIN}}/v1/graphql
      DOCKER_REGISTRY: ${{env.REGISTRY_REGION}}-docker.pkg.dev
      DOCKER_PATH: ${{env.DOCKER_REGISTRY}}/${{env.PROJECT_ID}}/${{env.REGISTRY_REPO}}
      BACKEND_TAG: ${{env.DOCKER_PATH}}/backend:pr-${{github.event.number}}
      BACKEND_HOST: ${{env.BACKEND_SERVICE}}-${{env.CLOUDRUN_SUFFIX}}.${{env.DEPLOYMENT_DOMAIN}}
      SC_MIGRATE_URL: https://${{env.BACKEND_HOST}}/actions/migrateSourceCredAccounts?force=true
      HASURA_SERVICE: ${{env.DB_NAME}}
      HASURA_TAG: ${{env.DOCKER_PATH}}/hasura:pr-${{github.event.number}}
      FRONTEND_TAG: ${{env.DOCKER_PATH}}/frontend:pr-${{github.event.number}}

    steps:
      - name: Info
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event Name: $GITHUB_EVENT_NAME"
          echo "SHA: $GITHUB_SHA"
          echo "Branch: $GITHUB_REF"
          echo "Head: $GITHUB_HEAD_REF"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "Base: $GITHUB_BASE_REF"
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "GraphQL URL: $GRAPHQL_URL"
          echo "Backend Tag: $BACKEND_TAG"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{env.DOCKER_REGISTRY}}
          username: _json_key
          password: ${{secrets.GCP_SA_KEY}}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{env.PROJECT_ID}}
          service_account_key: ${{secrets.GCP_SA_KEY}}
          export_default_credentials: true

      - name: Delete Database of Hasura
        continue-on-error: true
        run: |
          wget -q https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod u+x cloud_sql_proxy
          ./cloud_sql_proxy -instances ${{env.CLOUDSQL_CONNECTION_NAME}} -dir /tmp/cloudsql &
          PID=$!
          sleep 10
          PGPASSWORD=${{secrets.GCP_POSTGRES_PASSWORD}} dropdb -h /tmp/cloudsql/${{env.CLOUDSQL_CONNECTION_NAME}} -U postgres ${{env.DB_NAME}} -f
          kill $PID

      - name: Create User and Database for Hasura
        run: |
          echo "DB_PASSWORD=$(cat /dev/urandom | tr -cd [:alnum:] | head -c 16)" >> $GITHUB_ENV
          gcloud -q sql users create ${{env.DB_NAME}} -i ${{env.CLOUDSQL_INSTANCE_NAME}} --password ${{env.DB_PASSWORD}}
          gcloud -q sql databases create ${{env.DB_NAME}} -i ${{env.CLOUDSQL_INSTANCE_NAME}}

      - name: Undeploy Backend
        continue-on-error: true
        run: gcloud -q run services delete ${{env.BACKEND_SERVICE}} --region ${{env.CLOUDRUN_REGION}}

      - name: Delete Backend Image
        continue-on-error: true
        run: gcloud -q artifacts docker images delete ${{env.BACKEND_TAG}}

      - name: Build Backend Container
        uses: mattes/cached-docker-build-action@v1
        with:
          args: ". -f ./docker/backend/Dockerfile --tag ${{env.BACKEND_TAG}} --build-arg GRAPHQL_HOST=${{env.GRAPHQL_HOST}} --build-arg GRAPHQL_DOMAIN=${{env.GRAPHQL_DOMAIN}}"
          cache_key: "${{ hashFiles('packages/backend/**') }}"

      - name: Push Backend Container
        run: docker push ${{env.BACKEND_TAG}}

      - name: Deploy Backend
        run: |
          gcloud -q run deploy ${{env.BACKEND_SERVICE}} \
            --image ${{env.BACKEND_TAG}} \
            --region ${{env.CLOUDRUN_REGION}} \
            --port ${{env.BACKEND_PORT}} \
            --cpu 1 \
            --memory 512Mi \
            --ingress all \
            --allow-unauthenticated \
            --max-instances 1 \
            --set-env-vars HASURA_GRAPHQL_ADMIN_SECRET=metagame_secret,GITHUB_API_TOKEN=${{secrets.GH_API_TOKEN}},SOURCECRED_LEDGER_BRANCH=master

      - name: Undeploy Hasura
        continue-on-error: true
        run: gcloud -q run services delete $HASURA_SERVICE --region $CLOUDRUN_REGION

      - name: Delete Hasura Image
        continue-on-error: true
        run: gcloud -q artifacts docker images delete $HASURA_TAG

      - name: Build Hasura Container
        uses: mattes/cached-docker-build-action@v1
        with:
          args: "./hasura -f ./hasura/Dockerfile --tag $HASURA_TAG --build-arg BACKEND_HOST=$BACKEND_HOST --build-arg BACKEND_PROTOCOL=https"
          cache_key: "${{ hashFiles('hasura/**') }}"

      - name: Push Hasura Container
        run: docker push $HASURA_TAG

      - name: Deploy Hasura
        run: |
          gcloud -q run deploy $HASURA_SERVICE \
            --image $HASURA_TAG \
            --region $CLOUDRUN_REGION \
            --port $HASURA_PORT \
            --cpu 1 \
            --memory 512Mi \
            --ingress all \
            --allow-unauthenticated \
            --add-cloudsql-instances $CLOUDSQL_CONNECTION_NAME \
            --max-instances 1 \
            --set-env-vars HASURA_GRAPHQL_DATABASE_URL=postgres://${DB_NAME}:${DB_PASSWORD}@/${DB_NAME}?host=/cloudsql/${CLOUDSQL_CONNECTION_NAME},HASURA_GRAPHQL_ADMIN_SECRET=metagame_secret,HASURA_GRAPHQL_SERVER_PORT=${HASURA_PORT},HASURA_GRAPHQL_ENABLE_CONSOLE=true

      - name: Undeploy Frontend
        continue-on-error: true
        run: gcloud -q run services delete $FRONTEND_SERVICE --region $CLOUDRUN_REGION

      - name: Delete Frontend Image
        continue-on-error: true
        run: gcloud -q artifacts docker images delete $FRONTEND_TAG

      - name: Build Frontend Container
        uses: mattes/cached-docker-build-action@v1
        with:
          args: ". -f ./docker/frontend/Dockerfile --tag $FRONTEND_TAG --build-arg GRAPHQL_HOST=${HASURA_SERVICE}-${CLOUDRUN_SUFFIX} --build-arg GRAPHQL_DOMAIN=$DEPLOYMENT_DOMAIN"
          cache_key: "${{ hashFiles('packages/web/**', 'packages/design-system/**') }}"

      - name: Push Frontend Container
        run: docker push $FRONTEND_TAG

      - name: Deploy Frontend
        run: |
          gcloud -q run deploy $FRONTEND_SERVICE \
            --image $FRONTEND_TAG \
            --region $CLOUDRUN_REGION \
            --port $FRONTEND_PORT \
            --cpu 1 \
            --memory 512Mi \
            --ingress all \
            --max-instances 1 \
            --allow-unauthenticated

      - name: Seed Database
        run: |
          mv package.json package.json.temp
          npm install --no-package-lock --no-save node-fetch
          mv package.json.temp package.json
          LOCAL_GRAPHQL_URL="$GRAPHQL_URL" \
            LOCAL_BACKEND_ACCOUNT_MIGRATION_URL="$SC_MIGRATE_URL" \
            yarn hasura:seed-local-db

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Successfully deployed a preview of this pull request:

            * [Frontend](https://${FRONTEND_SERVICE}-${CLOUDRUN_SUFFIX}.${DEPLOYMENT_DOMAIN})
            * [Hasura](https://${HASURA_SERVICE}-${CLOUDRUN_SUFFIX}.${DEPLOYMENT_DOMAIN})
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
